### ISSUE TITLE
Dependency cert-manager missing from v0.1.14 on

### ISSUE THREAD

**Issue by numbnut** [spotify/flink-on-k8s-operator#112]
I recently tried out the new release v0.1.14 and ran into the problem that make deploy would fail with the following error message.

```
$ make deploy IMG=ghcr.io/spotify/flink-operator:v0.1.14
[...]
service/flink-operator-webhook-service created
deployment.apps/flink-operator-controller-manager created
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
mutatingwebhookconfiguration.admissionregistration.k8s.io/flink-operator-mutating-webhook-configuration created
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
validatingwebhookconfiguration.admissionregistration.k8s.io/flink-operator-validating-webhook-configuration created
Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource (post certificates.cert-manager.io)
Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource (post issuers.cert-manager.io)
make: *** [deploy] Error 1
```

The problem is that the CRDs for `Certificate` and `Issuer` are missing. I found out that they are provided by the cert-manager project.

Installing cert-manager fixes the problem, but I wanted to report this, because I think it would be nice to have this documented or fixed in the build logic.

```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
```

If you guide me I could try to provide a pull request.

**Comment by regadas** [comment]
Hi @numbnut! Yes! `v0.1.14` has dependency on cert-manager; The idea is not to provide it as part of the build but to reference it in the docs; Docs are just missing an update.

**Comment by numbnut** [comment]
Hi @regadas , ok that is good to hear. Then I was on the right track. Thanks for pointing that out.

**Comment by numbnut** [comment]
Hi @regadas , maybe one more thing. When touching the docs it would be really great to point out the version of cert-manager which is supported. Thank you!
