### ISSUE TITLE
Questions about webhook

### ISSUE THREAD

**Issue by pjthepooh** [spotify/flink-on-k8s-operator#148]
I have noticed that disabling webhook, specifically MutatingWebhook, will cause job submitter hangs after submitting the job  successfully and other unexpected behaviors. The reason why asking this is because installing webhook can be potentially dangerous as it impacts every single API call that K8S makes and they have to be rigorously monitored. I want to better understand what features are using webhook, and what could be causing the issue when there is no MutatingWebhook in place, and the motivation of this design. Any insights will be appreciated. 

cc: @regadas @elanv

**Comment by pjthepooh** [comment]
After some digging, i found that mutating webhook is used to set default values in [flinkcluster_default.go](https://github.com/spotify/flink-on-k8s-operator/blob/5f2c73a16f9040cb06cd9665e6a59b77d2280709/api/v1beta1/flinkcluster_default.go). When mutating webhook is disabled, job submitter will be run in Blocking mode vs Detached mode because of [this logic](https://github.com/spotify/flink-on-k8s-operator/blob/5f2c73a16f9040cb06cd9665e6a59b77d2280709/api/v1beta1/flinkcluster_default.go#L226-L230) along with other potential unexpected behavior due other other default values not being set.

Another note is the CRD doc is not updated , i.e. not reflecting the actual available fields defined in the CRD yaml, e.g. job.mode, JM.replicas

**Comment by regadas** [comment]
Hi @pjthepooh yup pretty much. The mutation webhook only adds defaults. I'll close this now ... feel free to open it if you want to keep discussing it.
