### ISSUE TITLE
Manager OOM errors

### ISSUE THREAD

**Issue by Oliver-Sellwood** [spotify/flink-on-k8s-operator#161]
The default resources for the cluster manager pod seem a bit low (20Mi and 30Mi) and I constantly get OOM errors.

Does this indicate I am doing something wrong or would it make sense for me to submit a PR to bump these?

I have been using 100Mi and  150Mi and that solves it (but I haven't tried to tune this)

**Comment by regadas** [comment]
Hey @Oliver-Sellwood sorry for the late reply!

yup I agree that we can raise the defaults a little bit more! Could submit a PR?

**Comment by regadas** [comment]
Closed via #169
