### ISSUE TITLE
Question: Why initContainers (for JM, TM) and logConfig in the CRD is not getting configured while creating the FlinkCluster.

### ISSUE THREAD

**Issue by guruprasathT** [spotify/flink-on-k8s-operator#179]
Hi,
Let me explain the case below. Please give your valuable suggestion.
```
[asis]
- Using flink-operator:v1beta1-6 (We know that initContainers, logConfig) is not supported in this flink-operator-controller-manager version.
- But CRD was installed with logConfig, initContainers (for JM, TM deployments) fields on the first time. (i.e we installed CRD from v1beta1-8 tag version)

[tobe]
- Upgrade operator to use flink-operator:v1beta1-8 or latest 
- Deploy flinkClusters but the "initContainers" and "logConfig" are not getting configured only for JM and TM pods and neither could see in kubectl describe flinkcluster testCluster.
```
I looked into `operator-controller-manager` log but there is no error/warn message why those fields are not recognized.

**Comment by regadas** [comment]
Hi @guruprasathT `v1beta1-X` versions are remainders of the Google fork and those are old versions; you should use the latest version available [here](https://github.com/volcano-sh/volcano/pull/1345).

Let us know if you are still seeing issues.

**Comment by guruprasathT** [comment]
Thanks. I believe you are referring latest version to [here](https://github.com/spotify/flink-on-k8s-operator/pkgs/container/flink-operator)

I will update the CRD and try with the latest version (i.e mentioned above) this coming week and update here.

**Comment by regadas** [comment]
Closing this now please reopen if issue still persists.
