### ISSUE TITLE
Generate CRD docs

### ISSUE THREAD

**Issue by regadas** [spotify/flink-on-k8s-operator#190]
CRD docs are a lot better thanks to @moonsub-kim! 

However, I was having a look at them and even though they are easier to consume I feel that they are a bit harder to maintain and we still have the issue that these docs are not being updated as they should.

We need to auto-gen these docs based on the CRD types; a possible solution could be https://github.com/ahmetb/gen-crd-api-reference-docs

**Comment by regadas** [comment]
#191 is an initial stab to some degree it's not as readable but given the fact that this is generated docs and look nice I'm totally ok with that.

**Comment by moonsub-kim** [comment]
So good! I added some additional comment into crd.md in #186
I will add the comments written from crd.md into the flinkcluster_types.go after #191 is merged

**Comment by regadas** [comment]
@moonsub-kim Thanks!
