### ISSUE TITLE
CR Yaml for QuickStart example may need some fix

### ISSUE THREAD

**Issue by bgeng777** [spotify/flink-on-k8s-operator#208]
Hi there,
I have followed the instructions in [User Guide](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/user_guide.md) to try the flink k8s operator. However, after directly typing commands from the guide, I met such error:
```bash
kubectl apply -f config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml
kubectl apply -f config/samples/flinkoperator_v1beta1_flinkjobcluster.yaml
```
![image](https://user-images.githubusercontent.com/80749729/149440293-2f395c4a-09ff-4002-9fa6-3715a8309819.png)

My k8s client version is v1.23.1. 

After checking our codes and API doc, I add those missed fields in the sample yaml and both of these 2 commands can work as expected. As a beginner of this community, I am not sure if my modification are necessary. If I miss something, please let me know. If the samples yaml should be updated due to newer k8s version for sure, I am welcome to contribute my fix.
Thanks!

**Comment by haoxins** [comment]
I'm working on this, see https://github.com/spotify/flink-on-k8s-operator/pull/204
welcome to give some ideas

**Comment by bgeng777** [comment]
> I'm working on this, see #204 welcome to give some ideas

hi haoxin, thanks a lot for the reply. It is great to know that you have done some work on this! 
I have one follow up: have you ever met any validation error like my post when running the example?

Besides, for your #204, due to my experience of using flink, for example job like WordCount, 1GiB for both JM and TM should be enough. But I also met same resource problem when setting TM's memory to be 1024MiB for running the example. I increase TM's memory to 2048 as well. But I think for JM, 1024 should be fine.

**Comment by haoxins** [comment]
Maybe you need to decrease the default config?

Below conf is copied from the Flink image `1.14.2`

```
flink@9f93f0c3891c:~$ cat conf/flink-conf.yaml | grep memory
# The total process memory size for the JobManager.
# Note this accounts for all memory usage within the JobManager process, including JVM metaspace and other overhead.
jobmanager.memory.process.size: 1600m
# The total process memory size for the TaskManager.
# Note this accounts for all memory usage within the TaskManager process, including JVM metaspace and other overhead.
taskmanager.memory.process.size: 1728m
# To exclude JVM metaspace and overhead, please, use total Flink memory size instead of 'taskmanager.memory.process.size'.
```

**Comment by bgeng777** [comment]
You are right about the flink config. My bad for forgetting the default JM memory config in flink yaml.
But I think my problem is not about flink. Instead, it is something wrong in the flinkoperator_v1beta1_flinkjobcluster.yaml in my environment. It seems that you have not met such error. It may be due to my k8s version or something else. I may keep this issue open for 1 or 2 weeks to see if there are any other people facing this problem. If not, I will close this issue. 
Again, @haoxins thanks for your help~

**Comment by haoxins** [comment]
>  It may be due to my k8s version or something else.

I use K8s 1.21 for this testing~

**Comment by bgeng777** [comment]
close this issue as there are no other relevant cases.
