### ISSUE TITLE
Cancel running Flink job Failed（Is cancel running flink job  must use with the savepoint）

### ISSUE THREAD

**Issue by hejiefang** [spotify/flink-on-k8s-operator#214]
Is cancel running flink job  must use with the savepoint？Or cancel running flink job only used in update?
When use  `kubectl annotate flinkclusters <CLUSTER-NAME> flinkclusters.flinkoperator.k8s.io/user-control=job-cancel` to cancel a jobcluster without setting the savepointsDir，the flink-operator-controller-manager failed with the log

`{"level":"info","ts":1642668111.7550068,"logger":"controllers.FlinkCluster","msg":"Trigger savepoint for update","cluster":"default/flinkjobcluster-sample","jobID":"8e964772d5b0ec2860567f82703523cf"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1436a8b]

goroutine 306 [running]:
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterReconciler).triggerSavepoint(0xc0015b0300, {0xc00159d320, 0x20}, {0x17acabf, 0x6}, 0x0)
        /workspace/controllers/flinkcluster_reconciler.go:846 +0x1ab
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterReconciler).trySuspendJob(0xc0015b0300)
        /workspace/controllers/flinkcluster_reconciler.go:660 +0x13b
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterReconciler).reconcileJob(0xc0015b0300)
        /workspace/controllers/flinkcluster_reconciler.go:594 +0xdbc
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterReconciler).reconcile(0xc0015b0300)
        /workspace/controllers/flinkcluster_reconciler.go:111 +0x189
github.com/spotify/flink-on-k8s-operator/controllers.(*FlinkClusterHandler).reconcile(0xc001051c18, {0x17b2411, 0x4}, {{{0xc0014fb3c9, 0x25d9d20}, {0xc00149fdb8, 0x203000}}})
        /workspace/controllers/flinkcluster_controller.go:223 +0xca5
github.com/spotify/flink-on-k8s-operator/controllers.(*FlinkClusterReconciler).Reconcile(0xc0008a2340, {0x19bf0b8, 0xc0015ba4e0}, {{{0xc0014fb3c9, 0x7}, {0xc00149fdb8, 0x16}}})
        /workspace/controllers/flinkcluster_controller.go:84 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000382a00, {0x19bf010, 0xc00093c000}, {0x162dec0, 0xc0015b69c0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000382a00, {0x19bf010, 0xc00093c000})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2`

**Comment by regadas** [comment]
Hi @hejiefang Thanks for reporting this.

This was indeed a bug addressed on #223. Canceling jobs should work for both scenarios, session and job cluster. Please re-open if this is still an issue for you.
