### ISSUE TITLE
[Proposal] Add tolerations attribute under spec.job attribute

### ISSUE THREAD

**Issue by Archangelix** [spotify/flink-on-k8s-operator#239]
The same attribute which exists under jobManager and taskManager should also exist under job attribute.

In our current case, the pod won't be allocated to any node unless this 'tolerations' attribute is specified. Currently we're using some webhook just to add this attribute. Adding it in the CRD would be a more elegant solution.

**Comment by regadas** [comment]
Hi @Archangelix! adding that makes total sense. Let me know if you want to take a stab at it.

**Comment by regadas** [comment]
Hi @Archangelix I went ahead and add it, coz I was actually needing it myself 😄
