### ISSUE TITLE
unable to find a version that was supported for platform darwin/arm64 when execute make test

### ISSUE THREAD

**Issue by Grypse** [spotify/flink-on-k8s-operator#289]
make test

`
 flink-on-k8s-operator/bin/controller-gen "crd:maxDescLen=0,trivialVersions=true,preserveUnknownFields=false,generateEmbeddedObjectMeta=true" rbac:roleName=manager-role webhook paths="./apis/.../v1beta1/..." output:crd:artifacts:config=config/crd/bases 
\\# remove status field as they interfer with ArgoCD and Google config-sync
\\# https://github.com/kubernetes-sigs/controller-tools/issues/456
 yq -i e 'del(.status)' config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
 /flink-on-k8s-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./apis/.../v1beta1/..."
 go fmt ./...
 go vet ./...
 go mod tidy
 unable to find a version that was supported for platform darwin/arm64
 rm -rf config/test && mkdir -p config/test/crd
 /flink-on-k8s-operator/bin/kustomize build config/crd > config/test/crd/flinkoperator.k8s.io_flinkclusters.yaml
 KUBEBUILDER_ASSETS="" go test ./... -coverprofile cover.out
 ?       github.com/spotify/flink-on-k8s-operator        [no test files]
 ?       github.com/spotify/flink-on-k8s-operator/apis/flinkcluster/v1alpha1     [no test files]
 Running Suite: v1beta1 Suite - /flink-on-k8s-operator/apis/flinkcluster/v1beta1 
Random Seed: 1645608488
`

Runtime info: MacBook Pro with M1 chip.

**Comment by regadas** [comment]
Yeah I'm sensing that the versions we are using do not take into account different arch's; I'll try to have a look at this, but if you have time PR's to address this would be very welcomed! 😄

**Comment by acechef** [comment]
You can temporarily solve this problem by this answer https://github.com/kubernetes-sigs/controller-runtime/issues/1657#issuecomment-988484517 @Grypse

**Comment by regadas** [comment]
I just got my hands on an M1 machine; should be able to address this soon:tm: but if any of you wants to go ahead, let me know.

**Comment by regadas** [comment]
This should be addressed now.
