### ISSUE TITLE
Replace `gcr.io/flink-operator/deployer:webhook-cert` in the Helm charts

### ISSUE THREAD

**Issue by haoxins** [spotify/flink-on-k8s-operator#303]
I think we should replace the image `gcr.io/flink-operator/deployer:webhook-cert` in the Helm charts.

**Comment by regadas** [comment]
Sorry for late reply @haoxins indeed we should and ref cert-manager instead.

**Comment by regadas** [comment]
Do you think you can take a stab at this?

**Comment by nickcaballero** [comment]
This is was done as part of https://github.com/spotify/flink-on-k8s-operator/pull/500.
