### ISSUE TITLE
job submitter doesn’t succeed in reading fields from the flink-conf.yaml

### ISSUE THREAD

**Issue by GilShmaya** [spotify/flink-on-k8s-operator#324]
Hey,
We are having an issue where the job submitter doesn’t succeed in reading some fields from the flink-conf.yaml file (the job manager and task managers do read it well). 
Those fields are added using the [flinkProperties] (https://github.com/spotify/flink-on-k8s-operator/blob/master/docs/crd.md#:~:text=containers.%20More%20info-,flinkProperties,-object%20(keys%3Astring%2C%20values%3Astring) configuration flag have no effect on the job-submitter pod.

Do you have any ideas why it could happen?

Thanks in advance,
Gil

**Comment by regadas** [comment]
Hi @GilShmaya Are you still facing this issue still relevant?

**Comment by regadas** [comment]
Since there's no response let's close this for now. Re-open if needed. Thank you!
