### ISSUE TITLE
Remote job jar without init container

### ISSUE THREAD

**Issue by CLevasseur** [spotify/flink-on-k8s-operator#343]
We'd like to set the cluster's job jar location to a cloud storage location and have the job submitter fetch it before executing `flink run`.

There seem to be 2 distinct ways to use remote job jars according to the documentation:

- Using init containers: https://github.com/spotify/flink-on-k8s-operator/blob/master/config/samples/flinkoperator_v1beta1_remotejobjar.yaml
- By adding the right connector (GCS only): https://github.com/spotify/flink-on-k8s-operator/tree/master/images/flink#create-a-flink-cluster

Ideally, we'd like to go for the second solution with multiple cloud storages but the documentation seems outdated, since the job-submitter passes the remote jar location to `flink run` [here](https://github.com/spotify/flink-on-k8s-operator/blob/ffd9ec7cdad8370662847223b4cc4b2b91154433/controllers/flinkcluster/flinkcluster_submit_job_script.go#L134), but flink CLI expects the jar to be available locally and throws an error saying the file doesn't exist.

Is that feature still supposed to work ? What would be the best approach to make it work ?

**Comment by regadas** [comment]
Hi @CLevasseur!

> By adding the right connector (GCS only): https://github.com/spotify/flink-on-k8s-operator/tree/master/images/flink#create-a-flink-cluster

This way is deprecated and the recommended way is to use init containers and yes the documentation is indeed outdated 😢 Any help keeping it up to date is well appreciated.

**Comment by CLevasseur** [comment]
Hi @regadas, thanks for the answer :) Unfortunately, init containers won't work in our case for internal reasons. 
Apache has released [another operator](https://github.com/apache/flink-kubernetes-operator) recently and [they plan on supporting remote jars](https://cwiki.apache.org/confluence/display/FLINK/FLIP-215%3A+Introduce+FlinkSessionJob+CRD+in+the+kubernetes+operator) without relying on init containers so we will probably switch.

Thanks for your work, this helped us a lot!
