### ISSUE TITLE
Where to view logs after submitting a job

### ISSUE THREAD

**Issue by MrHyson** [spotify/flink-on-k8s-operator#350]
![image](https://user-images.githubusercontent.com/30997542/160845813-6216e67b-35e0-4caf-bc66-72ef4f4c391e.png)
apiVersion: batch/v1
kind: Job
metadata:
namespace: flink-operator-system
name: my-job-submitter
spec:
template:
spec:
containers:
- name: wordcount
image: flinkd:v1
args:
- /opt/flink/bin/flink
- run
- -m
- flinksessioncluster-jobmanager:8081
- /opt/flink/data--SNAPSHOT.jar
- dev
restartPolicy: Never

**Comment by regadas** [comment]
To have better logging you should look into [`logConfig`](https://github.com/spotify/flink-on-k8s-operator/blob/master/docs/crd.md) property and tweak it to your needs. You should also avoid deploying jobs in the same namespace as the operator.

Feel free to reopen if you still have issues.
