### ISSUE TITLE
Rework Helm charts

### ISSUE THREAD

**Issue by regadas** [spotify/flink-on-k8s-operator#375]
Helm charts are not in a good state right now as they are a bit disconnected from the kustomize resources.

We should align the definitions and make the charts a part of the release.

**Comment by saminahbab** [comment]
Can you show me where the kustomize resources are? 
currently trying to use the helm chart, if you are telling me that the helm chart is critically wrong, then I would like to understand the best place to install from

**Comment by regadas** [comment]
Hi @saminahbab the kustomize resources are available under releases https://github.com/spotify/flink-on-k8s-operator/releases/download/v0.4.0/flink-operator.yaml

**Comment by Sudokamikaze** [comment]
Also I would like to mention, Helm charts are using `gen-cert.yaml` which generates secret by openssl instead of relying on cert-manager (just like kustomization way does)
It should be reworked as well as it doesn't work right now:

```
"creationTimestamp":<nil> "name":"webhook-server-cert" "namespace":"flink-operator-system"]]}
from server for: "STDIN": secrets "webhook-server-cert" is forbidden: User "system:serviceaccount:flink-operator-system:flink-sa" cannot get resource "secrets" in API group "" in the namespace "flink-operator-system"
```
In logs on `cert-job` job

**Comment by heumsi** [comment]
Is there any further progress?

**Comment by jiamin13579** [comment]
I try to fix it
#460

**Comment by nickcaballero** [comment]
Tried to address by updating the existing script - #500.

**Comment by nickcaballero** [comment]
Given that the `update_template.sh` is now sourcing directly from the Kustomize output, is the next step here to somehow incorporate the Helm chart updates as part of new releases?

**Comment by regadas** [comment]
@nickcaballero short answer to that is yes!
