### ISSUE TITLE
How the operator handles migration of StatefulSet from node to node

### ISSUE THREAD

**Issue by canopenerda** [spotify/flink-on-k8s-operator#403]
Hi team,

I'm planning to use this operator to manage over 10000 flink clusters on k8s. But I have one concern that is how the operator handles a running flink cluster when the node it runs on were not available, it seems without proper orchestration, it could result in data loss.

**Comment by nickcaballero** [comment]
I think this is generally out of scope for the operator. This would be better handled by Flink's [Kubernetes HA Services](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/ha/kubernetes_ha/).

**Comment by canopenerda** [comment]
@nickcaballero Thanks Nick! I adopted the official flink operator which natively supports HA.

**Comment by regadas** [comment]
Better HA support will come soon as well for us. Thanks for raising this.
