### ISSUE TITLE
Ingress backend service port name must be no more than 15 characters

### ISSUE THREAD

**Issue by mangrrua** [spotify/flink-on-k8s-operator#450]
When I want to enable Ingress, operator throws exception like below;

`
{"logger":"controllers.FlinkCluster","msg":"Failed to create ingress","cluster":"test/mydeploymentname","component":"JobManager","error":"Ingress.extensions \"mydeploymentname-jobmanager\" is invalid: spec.rules[0].http.paths[0].backend.service.port.name: Invalid value: \"mydeploymentname-jobmanager\": must be no more than 15 characters"}`

When I check the source code, I've found that;
https://github.com/spotify/flink-on-k8s-operator/blob/v0.4.1-beta.2/controllers/flinkcluster/flinkcluster_converter.go#L394

Kubernetes don't allow the port names more than 15 characters, so how can I solve this issue?

**Comment by regadas** [comment]
Hey @mangrrua do you think you can push a fix?
