### ISSUE TITLE
HPA not creating new pods on scale event

### ISSUE THREAD

**Issue by mttcnnff** [spotify/flink-on-k8s-operator#639]
We have a job which we want to run with autoscaling and have configured it via the FlinkCluster spec. The HPA gets created and seems to correctly calculate the number of workers, however it does not actually create those pods after initial creation of the cluster.

**Comment by regadas** [comment]
Hi @mttcnnff let's sync on this over slack; If HPA is created but pods are not spawned then smth else is going on that it's not entirely related with the operator.

**Comment by regadas** [comment]
This should be addressed in the latest release https://github.com/spotify/flink-on-k8s-operator/releases/tag/v0.5.0
