### ISSUE TITLE
Should we encourage the community to contribute to your fork?

### ISSUE THREAD

**Issue by sv3ndk** [spotify/flink-on-k8s-operator#82]
Hi @regadas ,

This is not an issue, though I was not sure how else to start the conversation.

As you know, the original flink-on-k8s-operator is no longer maintained, I and several others have submitted PR to it but couldn't get them merged.

I'm happy to discover your fork seems active. Do you plan to continue working on this? Is it useful that I re-submit my PR here? Is it OK if I encourage other contributors to do the same?

Thanks a lot,

S

**Comment by regadas** [comment]
Hi @sv3ndk!

> I'm happy to discover your fork seems active. Do you plan to continue working on this? Is it useful that I re-submit my PR here? Is it OK if I encourage other contributors to do the same?

Yes, feel free to contribute back and let others know! The plan is to keep this one moving forward.

Thanks for reaching out!

**Comment by maver1ck** [comment]
Hi @regadas,
Nice to hear that.
Do you (you as Spotify) have any plan to increase bus factor of this project ?

**Comment by shashken** [comment]
Hey, we have the same problem with this repo (started in april when I opened https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/441)
tried to move things from the slack channel but no luck there.
We have our own private fork with many changes (major concurrency bug fix, savepoint taking imrovements, k8s 1.20+ support, etc..)
Do you guys want to talk maybe about this project and its open source future so we can join our efforts?

**Comment by shashken** [comment]
? @sv3ndk @regadas

**Comment by regadas** [comment]
@shashken Yes feel free to send PR's! some things might have been already addressed but yeah every contrib is very much welcomed!
