### ISSUE TITLE
Make deploy failes for Kubernetes v1.21.2

### ISSUE THREAD

**Issue by numbnut** [spotify/flink-on-k8s-operator#83]
I'm trying to build and deploy the operator using Docker with Kubernetes on MacOS, but deploying it fails unfortunately.

Environment

Docker: v20.10.7
Kubernetes: v1.21.2
MacOS: 11.5.1

I use the following commands.

```
make operator-image push-operator-image IMG=localhost:5000/flink-operator:latest
make deploy IMG=localhost:5000/flink-operator FLINK_OPERATOR_NAMESPACE=flink-operator WATCH_NAMESPACE=default
```

The `make deploy` command fails with the following error.

```
go: creating new go.mod: module tmp
go get: added sigs.k8s.io/controller-tools v0.6.1
/Users/niklaswilcke/go/bin/controller-gen "crd:maxDescLen=0,trivialVersions=true,generateEmbeddedObjectMeta=true" rbac:roleName=manager-role webhook paths="./api/v1beta1/..." output:crd:artifacts:config=config/crd/bases
kubectl kustomize config/crd > config/crd/bases/patched_crd.yaml
mv config/crd/bases/patched_crd.yaml config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
go mod tidy
kubectl apply -f config/crd/bases
The CustomResourceDefinition "flinkclusters.flinkoperator.k8s.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
make: *** [install] Error 1
```

I think this problem is related to the dependency `sigs.k8s.io/controller-tools v0.6.1`, which has been downgraded in the past to v0.2.4 to fix this issue and now you recently upgraded it to v0.6.1. Can you maybe give some information, why it has been upgraded and why this error could be triggered.

Thank you!

**Comment by clouddra** [comment]
I have encountered a similar error as well

```
Error: unable to parse option "crd:maxDescLen=0,trivialVersions=true,generateEmbeddedObjectMeta=true": [unknown argument "generateEmbeddedObjectMeta" (at <input>:1:61) extra arguments provided: "true" (at <input>:1:62)]
```

**Comment by regadas** [comment]
hi @numbnut I haven't tested yet with v1.21.2 but I'll take a look.

Using `controller-tools@0.2.4` was needed before to be able to run the operator with k8s `>1.18 but that has been addressed in this fork at least up until `v1.20.x` 

The newer`0.6.1` introduces `generateEmbeddedObjectMeta` which is required specifically to add the metadata for the `PersistentVolumeClaims` without it claims will not be deleted when the cluster is deleted;

@clouddra  check if your env is not using a previous version of `controller-tools`

**Comment by clouddra** [comment]
Hi @regadas. Using the right version of controller tools worked for me. 

However I did encounter another problem when deploying to v1.15.7.

```
kubectl kustomize config/crd > config/crd/bases/patched_crd.yaml
mv config/crd/bases/patched_crd.yaml config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
go mod tidy
kubectl apply -f config/crd/bases
error: unable to recognize "config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

The issue is likely due to the CRD's `apiVersion`. It worked after I modified manually the generated yaml manifest to match that of `apiextensions.k8s.io/v1beta1`. For anyone interested please refer to the [public gist](https://gist.github.com/clouddra/9dc0f098b289216456dbfbd0520183bc) for the changes made.

**Comment by numbnut** [comment]
Hi @regadas , thanks for the feedback. If I can somehow support you, please let me know.

**Comment by numbnut** [comment]
Hi @clouddra , I'm not sure to which Kubernetes version you are referring. Are all your comments referring to the version `v1.15.7`, which you are mentioning in the second comment? If this is the case I think it might be better to open a new ticket, because this one is focusing on `v1.21.x`.

**Comment by regadas** [comment]
I doubled checked the operator deployment on `k8s >=1.18` and it seems that there are no issues; 

I used our latest version:
```
make deploy IMG=ghcr.io/spotify/flink-operator:v0.1.13
```

Make sure `controller-tools` is on `0.6.1`

**Comment by numbnut** [comment]
Hi @regadas , thanks for checking it. I will take another look and try out your pre-built image. If I have some results I will report back.

**Comment by numbnut** [comment]
Hi @regadas ,
I can confirm that you prebuilt image is working on Docker for Mac. It seems that there are problems in the build chain on Docker for Mac or that I have misconfigured something.
Can you say something about MacOS compatibility?
Should I maybe create a new ticket about it?
Regards,
Niklas

**Comment by numbnut** [comment]
I checked again with the latest release 0.1.14 and the problem vanished. Since a lot of changes have been applied to the build logic I assume that this might have fixed the problem.
