### ISSUE TITLE
Missing securityContext Properties on CRD

### ISSUE THREAD

**Issue by numbnut** [spotify/flink-on-k8s-operator#94]
I have some problems migrating from the GoogleCloudPlatform/flink-on-k8s-operator. It looks like certain properties just vanished from the CRD. Please take a look at the following list.

taskManager / jobManager / image / job
1. securityContext.privileged
2. securityContext.allowPrivilegeEscalation
3. securityContext.readOnlyRootFilesystem
4. securityContext.capabilities

I checked the CRD, whether the properties may have been relocated, but I wasn't able to find them in a different place. Is there a reason for removing them? Please let me know, when something is missing to further assist the investigations.
Thank you very much!

**Comment by regadas** [comment]
Hi @numbnut not sure if I understand this; They are present in the CRD.

**Comment by numbnut** [comment]
Hi @regadas , thanks for the feedback. I will check again and come back to you. Maybe I managed to deploy a broken CRD.

**Comment by regadas** [comment]
No worries; we are actually improving the deployment process.

**Comment by numbnut** [comment]
Hi @regadas ,
I checked it and you where right about the `securityContext`. It is existing, but some sub properties are missing. I changed the description and only listed the missing ones. Can you say something about why they have been removed. With the GCP Operator they where working fine. Let me add them here as well.

```
taskManager / jobManager / image / job

    securityContext.privileged
    securityContext.allowPrivilegeEscalation
    securityContext.readOnlyRootFilesystem
    securityContext.capabilities
```

**Comment by acherla** [comment]
Upping this issue as we are seeing the same issue on our end as well.

**Comment by regadas** [comment]
Closing this issue in favor of #241 which outlines why these properties are missing.
