### ISSUE TITLE
autoSavepointSeconds Property doesn't have any effect

### ISSUE THREAD

**Issue by numbnut** [spotify/flink-on-k8s-operator#95]
No matter what I set in `job.autoSavepointSeconds` the savepoint interval will be roughly 15 minutes. Am I doing something wrong? This problem already exists in the original GoogleCloudPlatform operator and I hoped this might be fixed here.

Is this issue maybe related to https://github.com/spotify/flink-on-k8s-operator/issues/84?

Any help appreciated. Thank you very much!

**Comment by elanv** [comment]
I had improved and fixed savepoint related routines in PR #107 .
It seems to work fine about auto savepoint feature.
But for now, the job mode must be "Detached" because there is an issue as we are discussing in that PR.
