### ISSUE TITLE
Savepoint Cleanup during Runtime

### ISSUE THREAD

**Issue by numbnut** [spotify/flink-on-k8s-operator#96]
Hi,
when I start a job with savepoints enabled they are constantly piling up. As far as I can see there are only some cleanup policies available in case the job gets terminated. I'm wondering why there is no retention count or anything similar to get rid of stale savepoints during job runtime. Is this cleanup procedure supposed to be taken care of by the user? Maybe via a sidecar container? Maybe I'm getting something wrong. I would really appreciate to get some insights.
Thank you very much!

**Comment by clouddra** [comment]
One approach would be to set up a bucket lifecycle policy to expire/delete savepoint files that are older than `n` days

**Comment by numbnut** [comment]
Hi @clouddra , if I get your right this is an external approach as well and it assumes using S3 as a storage backend, right?

**Comment by clouddra** [comment]
Yes it is an external approach. I am using S3 but it should work for GCP as well.

**Comment by regadas** [comment]
I think setting up the lifecycle policy as @clouddra mention is actually the way to go; I don't see a reason for this to be operator's responsibility.
